### ISSUE TITLE
JSON from Twitter incorrectly formatted

### ISSUE THREAD

**Issue by penguinrunner** [n3mo/massmine#12]
The JSON being returned for multiple records is returning individual json objects on new lines instead of a data set. They should be returned within an array as seen in the tutorial video https://www.youtube.com/watch?v=Bm6z7K0k3Vg

The Twitter User search also appears to be the same. I have not played with any other API to verify those. 

I have attached the result of the following search:
[massmine --task=twitter-search --query=pokemon --count=10]

[pokemon-twitter-search.zip](https://github.com/n3mo/massmine/files/745324/pokemon-twitter-search.zip)

**Comment by n3mo** [comment]
Thanks for taking the time to submit an issue @penguinrunner. This is actually intended behavior as of version 1.0.0. The rationale was to make the JSON output consistent across (most) tasks--particularly those tasks capable of returning large results such as twitter-stream, and so that line-oriented algorithms could be leveraged during data analysis. With this approach, the user will never have to load a large JSON array into memory to retrieve data contained therein.

This does reflect a problem with the documentation video which is, unfortunately, a little slower to update. I'll make a note to address this in the online documentation at the very least until the tutorial videos can be updated.
