### ISSUE TITLE
Twitter-stream --dur is not working

### ISSUE THREAD

**Issue by tsadhana9** [n3mo/massmine#13]
Hi, I am using massmine --task=twitter-stream --query=love --count=300 --dur='2015-10-11 14:30:00' command but this command is not giving any data(output). I also tried with different queries and different dates and time.

**Comment by n3mo** [comment]
Hi! You can think of twitter-stream working this way: it runs forever, but is stopped when either `count` number of tweets have been received *OR* when the date specified in `dur` is reached (whichever event happens first). Because you're using a data from the past (2015), this stops the data collection immediately. If you change this to a date in the future it should then collect data.

**Comment by tsadhana9** [comment]
I gave the below command
massmine --task=twitter-stream --query=elections --count=30 --dur='2021-10-11 14:30:00'

I got the below error
Massmine: The following error occured: Unknown task requested

I tried with different queries and with different future dates.

could you please provide an working example for duration command ?

**Comment by n3mo** [comment]
Your new command is indeed valid, and worked as-is for me. Can you confirm:

(1) which version of massmine you are using (can be determined with `massmine -v`)
(2) what operating system you are using (and which distro if you're using linux)

**Comment by tsadhana9** [comment]
1) massmine 1.2.1
2) Ubuntu 20.04.1 LTS

**Comment by n3mo** [comment]
Thanks! If it isn't too much trouble, can you try to most recent version (1.2.2)?
