### ISSUE TITLE
tumblr-posts count is not working

### ISSUE THREAD

**Issue by tsadhana9** [n3mo/massmine#15]
I am trying to collect data from tumblr-posts. If I give query = kingjamesprogramming, count = 2 , massmine is collecting 20 posts  instead of 2. If I give query = kingjamesprogramming, count = 30, it is collecting 40 posts instead of 30.

**Comment by n3mo** [comment]
This is actually intentional (although undocumented) behavior. The rationale is simply that when querying Tumblr's API to retrieve data, the rate limit cost is the same when requesting any number of posts between 1-20. Because you save nothing by requesting, say 15 instead of 20 posts, massmine's behavior is to simply request posts in chunks of 20. I will grant you that this is unexpected from the user's standpoint however. I will update the documentation to reflect this. If you have a compelling reason why massmine should deliberately request less that 20-post chunks so as to return quantities such as 2 or 30, I would consider taking the time to implement a change. Thanks!
