### ISSUE TITLE
OSX installation 

### ISSUE THREAD

**Issue by rrrivando** [n3mo/massmine#16]
Hey I'm a beginner at command line stuff and despite the process looking straightforward, am having an issue getting massmine working. Here is what I am doing, 

_Download and running massmine>_
unzip massmine-1.4.0-OSX-11.zip
Archive:  massmine-1.4.0-OSX-11.zip
   creating: massmine/
  inflating: massmine/massmine.link  
  inflating: massmine/massmine       

_Then I move into the massmine directory and try the "help" function to see if it's working but I get an error>_
cd massmine
./massmine --help
_and get this>_
dyld: Library not loaded: /usr/local/opt/openssl@3/lib/libssl.3.dylib
  Referenced from: /Users/rrrivando/massmine/./massmine
  Reason: image not found
Abort trap: 6

Any clue where I am going wrong? I get the same error when I just click on the massmine exec file and run it that way too. I have tried running this on 2 different Macs, one running High Sierra and the other Monterey. 

Thanks.

**Comment by n3mo** [comment]
I'm not surprised that OpenSSL is the culprit. Ever since Apple dropped support for this standard it's been a game of cat and mouse trying to make this library portable. One solution (though admittedly not command-line beginner friendly), is to try to install the OpenSSL library itself. The easiest way (the way I also use) is with Homebrew. If you haven't used Homebrew before, here's the two-step process:

1. Install Homebrew (this is a one-line terminal command): [Homebrew](https://brew.sh/) 
2. Install OpenSSL with Homebrew:

```sh
brew install openssl@3
```

If you're willing to take these additional steps, I suspect this will solve your problem. If not, hopefully I can figure out why OpenSSL isn't as portable as I had hoped.
